spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    #password:
    #timeout: 6000ms  # 连接超时时长（毫秒）
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sigu_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: sigu
    password: 123456
    hikari:
      connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
      minimum-idle: 2               # 最小空闲连接数
      maximum-pool-size: 10         # 最大连接数
      auto-commit: true             # 自动提交
      idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
      connection-test-query: SELECT 1
      pool-name: SiguHikariCP


--- ############ 监控相关配置

# Actuator 配置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

# Spring Boot Admin 配置
spring:
  boot:
    admin:
      # Spring Boot Admin Server 服务端地址
      context-path: /monitor/admin
      client:
        # 指定 Spring Boot Admin Server 服务端地址
        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path}
        instance:
          service-host-type: IP